---
title: "00_mixing_experiment_h_RNAScope_figures"
author: "Mark Robinson, Izaskun Mallona & Giulia Moro"
format: 
  html:
    toc: true
    embed-resources: true
    keep_md: true
---

### Load packages, load data 

```{r,warning=FALSE, message=FALSE}

rm(list=ls())

library(SingleCellExperiment)
library(scran)
library(ggplot2)
library(dplyr)
library(scater)
library(reshape2)
library(UpSetR)
library(limma)
library(cowplot)
library(pheatmap)
library(readr)
library(plotROC)
library(ggpubr)
library(here)
library(RColorBrewer)
library(ggnewscale)
library(scales)
library(rmarkdown)
library(irlba)
library(viridis)
library(gridExtra)
library(googlesheets4)
library(tools)
library(gridExtra)
library(khroma)
library(ggrastr)

packageVersion("raster")

packageVersion("Matrix")

rdss <- dir(here("00_mixing_experiment"), "^mixing.*rds$", 
            recursive = TRUE, full.names = TRUE)

datadir <- dirname(rdss)[1] # folder where the .rds files are 

sce_nd<-readRDS(file.path(datadir, "sce_nd.rds"))

```

### Setting up knitr 

```{r}

knitr::opts_chunk$set(fig.width = 2.7,
               fig.height = 2.7,
               fig.align = "center",
               include = TRUE,
               dev = c("png","svg"),
               cache=TRUE,
               cache.lazy = FALSE,
               warning = TRUE,
               message = TRUE)

```

### Importing annotation file

```{r}

# read annotation info from GS
anno_url <- "https://docs.google.com/spreadsheets/d/1cvldF_VFA7FYuChoR9a4SIpYcZ1aS80yThNT3iP4T00/edit#gid=978414281"
anno_df <- read_sheet(anno_url, "transcript-regions-mark") 
anno_df<-anno_df[anno_df$Experiment=="Mixing",]
regs <- split(anno_df$Name_in_gtf_file, anno_df$region_name)

```

### Themes

```{r}

rock_roi_theme<-function(){
  theme(axis.text = element_text(size=7), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        legend.title=element_text(size=7,face="bold"),
        legend.text=element_text(size=7),
        aspect.ratio=1,
        legend.key.size = unit(0.5, 'cm'),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
}

rock_roi_theme_multiple_panels<-function(){
    theme(axis.text = element_text(size=7), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        legend.key.size = unit(0.5, 'cm'),
        legend.title=element_text(size=7,face="bold"),
        legend.text=element_text(size=7),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.border = element_rect(colour = "black", fill = NA))
}

```

### Defining colors to use

```{r}

myscale<-c(color("muted")(9), gray="darkgrey", 
             black = "black", darkorange = "darkorange",
             yellowgreen = "yellowgreen")

# defining colors for samples and for species

names(myscale) <- c("unmod","unmod_roi","rock","egfp_cds","rockroi","human","unknown","mouse","tdtom_cds","no_detection","doublets","low","high")

#plot(1:13, col=myscale, pch=19, cex=4)

```

### Species for sce_nd

```{r}

sce_nd$sample_id<-gsub("mixing_", "", sce_nd$sample_id)

ae_tso <- altExp(sce_nd,"tso_ontarget_multi")
ae_wta <- altExp(sce_nd,"wta_ontarget_multi")

df<-colData(sce_nd)

df$egfp_sum_cds<-colSums(assay(ae_tso,1)[regs$egfp_cds,,drop=FALSE])+colSums(assay(ae_wta,1)[regs$egfp_cds,,drop=FALSE])

df$egfp_sum<-colSums(assay(ae_tso,1)[regs$egfp_tx,,drop=FALSE])+colSums(assay(ae_wta,1)[regs$egfp_tx,,drop=FALSE])

mouse<-df[df$species=="mouse",]
human<-df[df$species=="human",]

```

### Reading RNAScope data

```{r}
egfp1 <- read.csv(file.path(datadir, "results_D02_100.csv"))
egfp2 <- read.csv(file.path(datadir, "results_D03_100.csv"))
wt <- read.csv(file.path(datadir, "results_D04_100.csv"))
tdtom <- read.csv(file.path(datadir, "results_D05_100.csv")) 

egfp1$sample<-"egfp1"
egfp2$sample<-"egfp2"
wt$sample<-"wt"
tdtom$sample<-"tdtom"

```

### Boxplot RNAScope

```{r}

tot<-bind_rows(egfp1,egfp2,wt,tdtom)

plot1<-ggplot(tot, aes(x=sample, y=nSpots)) + 
  geom_jitter(shape=16, position=position_jitter(0.3),aes(fill=sample,color=sample),alpha=0.3,size=0.1,show.legend = FALSE) + 
  geom_boxplot(width=0.8,outlier.shape=NA,show.legend = FALSE,alpha=0) +
  theme_bw() +
  rock_roi_theme() +
  scale_fill_manual(labels=c("egfp1","egfp2","tdtom","wt"),
                     values=c(myscale[["egfp_cds"]],myscale[["egfp_cds"]],myscale[["tdtom_cds"]],myscale[["no_detection"]]))+
  scale_color_manual(labels=c("egfp1","egfp2","tdtom","wt"),
                     values=c(myscale[["egfp_cds"]],myscale[["egfp_cds"]],myscale[["tdtom_cds"]],myscale[["no_detection"]]))

plot1<-rasterize(plot1, layers='Point', dpi=1000)

plot1

ggsave(file=file.path(datadir,"rnascopedetection.svg"), plot=plot1, width=1.9, height=1.9)

```

### Detction of UMIs for ORF and transgenes in sample

```{r,fig.width=5.4,fig.height=2.7}

sub_df_mouse<-as.data.frame(mouse[,c("egfp_sum_cds","egfp_sum","sample_id")])
colnames(sub_df_mouse)<-c("CDS","tx","sample_id")

table(sub_df_mouse$sample_id)

plottable<-melt(sub_df_mouse)

plottable$id<-paste0(plottable$sample_id,"_",plottable$variable)

samples<-c("unmod_CDS","unmod_tx","unmod_roi_CDS","unmod_roi_tx","rock_CDS","rock_tx","rockroi_CDS","rockroi_tx")

plot2<-ggplot(plottable, aes(x=factor(id,levels=samples), y=value,factor(id,levels=samples))) + 
  geom_jitter(shape=16, position=position_jitter(0.3),aes(fill=factor(id,levels=samples),color=factor(id,levels=samples)),size=0.1,show.legend = FALSE)+
  geom_boxplot(width=0.8,outlier.shape=NA,show.legend = FALSE,alpha=0)+
  theme_bw()+
  rock_roi_theme()+
  xlab("sample")+
  theme_bw()+
  rock_roi_theme()+
  xlab("sample")+
  scale_fill_manual(labels=samples, 
                     values=alpha(c(myscale[["unmod"]],myscale[["unmod"]],myscale[["unmod_roi"]],myscale[["unmod_roi"]],myscale[["rock"]],myscale[["rock"]],myscale[["rockroi"]],myscale[["rockroi"]]),c(rep(c(0.3,0.1),4))))+
  guides(colour = guide_legend(override.aes = list(size=3)))+
  scale_color_manual(labels=samples, 
                     values=alpha(c(myscale[["unmod"]],myscale[["unmod"]],myscale[["unmod_roi"]],myscale[["unmod_roi"]],myscale[["rock"]],myscale[["rock"]],myscale[["rockroi"]],myscale[["rockroi"]]),c(rep(c(0.3,0.1),4))))+
  guides(colour = guide_legend(override.aes = list(size=3)))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))
  
plot2<-rasterize(plot2, layers='Point', dpi=1000)

plot2

ggsave(file=file.path(datadir,"umisrnascope.svg"), plot=plot2, width=2.45, height=2.45)
                    

```

### Session info

```{r}

sessionInfo()

```

