---
title: "00_mixing_k_qualimap_coverages.qmd"
author: "Mark Robinson, Izaskun Mallona & Giulia Moro"
format: 
  html:
    toc: true
    embed-resources: true
    keep_md: true
---

### Load packages

```{r,warning=FALSE, message=FALSE}

rm(list=ls())
library(ggplot2)
library(quarto)
library(khroma)
library(here)
library(reshape2)

```

### Setting up knitr 

```{r}

knitr::opts_chunk$set(fig.width = 2.7,
               fig.height = 5.4,
               fig.align = "center",
               include = TRUE,
               dev = c("png","svg"),
               cache=TRUE,
               cache.lazy = FALSE,
               warning = TRUE,
               message = TRUE)

```

### Themes

```{r}

rock_roi_theme<-function(){
  theme(axis.text = element_text(size=7), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        legend.title=element_text(size=7,face="bold"),
        legend.text=element_text(size=7),
        aspect.ratio=1,
        legend.key.size = unit(0.5, 'cm'),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
}

rock_roi_theme_multiple_panels<-function(){
    theme(axis.text = element_text(size=7), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        legend.key.size = unit(0.5, 'cm'),
        legend.title=element_text(size=5,face="bold"),
        legend.text=element_text(size=5),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.border = element_rect(colour = "black", fill = NA))
}

```

### Defining colors

```{r}

myscale<-c(color("muted")(9), gray="darkgrey", 
             black = "black", darkorange = "darkorange",
             yellowgreen = "yellowgreen")

# defining colors for samples and for species

names(myscale) <- c("unmod","unmod_roi","rock","egfp_cds","rockroi","human","unknown","mouse","tdtom_cds","no_detection","doublets","unmod_n1","high")

#plot(1:13, col=myscale, pch=19, cex=4)

```

### Loading data

```{r}

getwd() # after opening the .Rproj file, getwd() should be "/Users/gimoro/figure_making_paper/rock_roi_paper"

rdss <- dir(here("00_mixing_experiment/data/qualimap"), "*.txt", 
            recursive = TRUE, full.names = TRUE)

datadir <- dirname(rdss)[1] # folder where the .rds files are 

samples<-c("unmod","unmod_roi","rock","rockroi")
modalities<-c("wta","tso")
total_coverages<-list()
total_coverages
for (i in samples){
  for (k in modalities){
    dir<-paste0(here("00_mixing_experiment/data/qualimap"),"/",i,"_",k,"/","raw_data_qualimapReport/coverage_profile_along_genes_(total).txt")
    total_coverages[[paste0(i,"_",k)]]<-read.table(dir)
    colnames(total_coverages[[paste0(i,"_",k)]])<-c("transcript position",paste0(i,"_",k))
  }
}

```

### Merging datasets

```{r}

merged_total_coverages<-data.frame(matrix(nrow=100,ncol=9))

colnames(merged_total_coverages)<-c("transcript position",names(total_coverages))
merged_total_coverages$"transcript position"<-total_coverages[[1]]$`transcript position`

for (i in names(total_coverages)){
  merged_total_coverages[,i]<-total_coverages[[i]][,2]
}

d <- melt(merged_total_coverages, id.vars="transcript position")
colnames(d)<-c("transcript_position","variable","value")

ggplot(d,aes(x=`transcript_position`,y=value,color=variable))+
  geom_line()+
  theme_bw()+
  rock_roi_theme()+
  ylab("coverage")+
  scale_color_manual(labels=c("unmod_wta","unmod_tso","unmod_roi_wta","unmod_roi_tso","rock_wta","rock_tso","rockroi_wta","rockroi_tso"),
                     values=alpha(c(myscale[["unmod"]],myscale[["unmod"]],myscale[["unmod_roi"]],myscale[["unmod_roi"]],myscale[["rock"]],myscale[["rock"]],myscale[["rockroi"]],myscale[["rockroi"]]),c(1,0.5,1,0.5,1,0.5,1,0.5)))

```

### Session info

```{r}

sessionInfo()

```

