---
title: "08_cell_lines_a_sce_object_generation"
format:
  html:
    toc: true
    embed-resources: true
editor_options: 
  chunk_output_type: console
---


## Load packages, load data

```{r, warning=FALSE, message=FALSE}

rm(list=ls())

library(SingleCellExperiment)
library(scran)
library(ggplot2)
library(dplyr)
library(scater)
library(reshape2)
library(UpSetR)
library(limma)
library(cowplot)
library(pheatmap)
library(readr)
library(plotROC)
library(here)
library(Matrix)
library(stringr)

sample<-"cell_lines"
run_mode<-"tso off- and ontarget unique"
wd<-"/Users/gimoro/figure_making_paper/rock_roi_paper/08_cell_line_analysis/data"

```

## Generating sce object for wta --> based on rock_roi_method code

```{r}

read_matrix <- function(mtx, cells, features, cell.column = 1, feature.column = 1, modality, wta_whitelist) {
  cell.barcodes <- read.table(
    file = cells,
    header = FALSE,
    row.names = cell.column)


  feature.names <- read.table(
    file = features,
    header = FALSE,
    row.names = feature.column)

  d <- as(readMM(mtx), 'CsparseMatrix')

  ## if (modality == 'wta') {
  ## colnames(d) <- gsub('_', '', rownames(cell.barcodes))
  ## } else if (modality == 'tso') {
  ##     ## remove the fixed parts of the TSO CBs
  ##     colnames(d) <- paste0(
  ##         substr(rownames(cell.barcodes), 1, 9),
  ##         substr(rownames(cell.barcodes), 9+4+1, 9+4+9),
  ##         substr(rownames(cell.barcodes), 9+4+9+4+1, 9+4+9+4+9))
  ## }

  colnames(d) <- rownames(cell.barcodes)
  rownames(d) <- rownames(feature.names)
  
  if (modality == 'tso') {
      d <- d[,wta_whitelist]
  }

  return(d)
}

```

## WTA data

```{r}

wta <- read_matrix(mtx = file.path(wd,'align_wta','leukemia_cell_lines','Solo.out', 'Gene', 'filtered', 'matrix.mtx'),
                   cells = file.path(wd,'align_wta', 'leukemia_cell_lines','Solo.out', 'Gene', 'filtered','barcodes.tsv'),
                   features = file.path(wd,'align_wta','leukemia_cell_lines', 'Solo.out', 'Gene', 'filtered','features.tsv'),
                   cell.column = 1,
                   feature.column = 1,
                   modality = 'wta')

wta_feat <- read.table(file.path(wd,'align_wta', 'leukemia_cell_lines','Solo.out', 'Gene', 'filtered','features.tsv'),
                       row.names = 1,
                       header = FALSE)

colnames(wta_feat) <- c("name", "type", "value")

```

## TSO data

```{r}

if (run_mode == 'tso ontarget multi') {
    mtso <- read_featurecounts(file.path(wd, 'multimodal', id, 'tso_featurecounted'),
                               wta_whitelist = colnames(wta))
    mwta <- read_featurecounts(file.path(wd, 'multimodal', id, 'wta_featurecounted'),
                               wta_whitelist = colnames(wta))
    
    (sce <- SingleCellExperiment(assays = list(wta = wta),
                                 altExps = list(wta_ontarget_multi = SummarizedExperiment(mwta),
                                                tso_ontarget_multi = SummarizedExperiment(mtso)),
                                 mainExpName = sample,
                                 rowData = wta_feat))

} else if (run_mode == 'tso off- and ontarget unique') {
    utso <- read_matrix(mtx = file.path(wd, 'align_tso', 'leukemia_cell_lines', 'Solo.out', 'Gene', 'raw', 'matrix.mtx'),
                   cells = file.path(wd, 'align_tso', 'leukemia_cell_lines',  'Solo.out', 'Gene', 'raw', 'barcodes.tsv'),
                   features = file.path(wd, 'align_tso', 'leukemia_cell_lines',  'Solo.out', 'Gene', 'raw', 'features.tsv'),
                   cell.column = 1,
                   feature.column = 1,
                   modality = 'tso',
                   wta_whitelist = colnames(wta))


    (sce <- SingleCellExperiment(assays = list(wta = wta, tso_off_and_ontarget_unique = utso),
                            mainExpName = sample,
                            rowData = wta_feat))
} else if (run_mode == 'all') {

    mtso <- read_featurecounts(file.path(wd, 'multimodal', id, 'tso_featurecounted'),
                               wta_whitelist = colnames(wta))
    mwta <- read_featurecounts(file.path(wd, 'multimodal', id, 'wta_featurecounted'),
                               wta_whitelist = colnames(wta))
    utso <- read_matrix(mtx = file.path(wd, 'align_tso', id,  'Solo.out', 'Gene', 'raw', 'matrix.mtx'),
                   cells = file.path(wd, 'align_tso', id,  'Solo.out', 'Gene', 'raw', 'barcodes.tsv'),
                   features = file.path(wd, 'align_tso', id,  'Solo.out', 'Gene', 'raw', 'features.tsv'),
                   cell.column = 1,
                   feature.column = 1,
                   modality = 'tso',
                   wta_whitelist = colnames(wta))

    (sce <- SingleCellExperiment(assays = list(wta = wta, tso_off_and_ontarget_unique = utso),
                                 altExps = list(wta_ontarget_multi = SummarizedExperiment(mwta),
                                                tso_ontarget_multi = SummarizedExperiment(mtso)),
                                 mainExpName = sample,
                                 rowData = wta_feat))
}

assay(sce,"wta")

saveRDS(object = sce, file = file.path(wd, "cell_line.sce"))

```

## Session info

```{r}

sessionInfo()

```



