---
title: "03_first_mixing_experiment_g-mapping_stats_tso_data"
author: "Mark Robinson, Izaskun Mallona & Giulia Moro"
format: 
  html:
    toc: true
    embed-resources: true
    keep_md: true
---

### Load packages

```{r,warning=FALSE, message=FALSE}

rm(list=ls())

library(SingleCellExperiment)
library(scran)
library(ggplot2)
library(dplyr)
library(scater)
library(reshape2)
library(UpSetR)
library(limma)
library(cowplot)
library(pheatmap)
library(googlesheets4)
library(readr)
library(plotROC)
library(here)
library(RColorBrewer)
library(ggnewscale)
library(scales)
library(rmarkdown)
library(khroma)
library(irlba)
library(viridis)
library(gridExtra)
library(quarto)
library(Biostrings)
library(BSgenome)
library(rtracklayer)
library(GenomicRanges)
library(GenomicFeatures)
library(memes)
library(universalmotif)

```

### Setting up knitr 

```{r}

knitr::opts_chunk$set(fig.width = 2.7,
               fig.height = 2.7,
               fig.align = "center",
               include = TRUE,
               dev = c("png","svg"),
               cache=TRUE,
               cache.lazy = FALSE,
               warning = TRUE,
               message = TRUE)

```

### Themes

```{r}

rock_roi_theme<-function(){
  theme(axis.text = element_text(size=7), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        legend.title=element_text(size=7,face="bold"),
        legend.text=element_text(size=7),
        aspect.ratio=1, 
        legend.key.size = unit(0.5, 'cm'),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
}

rock_roi_theme_multiple_panels<-function(){
    theme(axis.text = element_text(size=7), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        legend.key.size = unit(0.5, 'cm'),
        legend.title=element_text(size=5,face="bold"),
        legend.text=element_text(size=5),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.border = element_rect(colour = "black", fill = NA))
}

```

### Defining colors

```{r}

myscale<-c(color("muted")(9), gray="darkgrey", 
             black = "black", darkorange = "darkorange",
             yellowgreen = "yellowgreen")

# defining colors for samples and for species

names(myscale) <- c("unmod","unmod_roi","rock","egfp_cds","rockroi","human","unknown","mouse","tdtom_cds","no_detection","doublets","unmod_n1","high")

#plot(1:13, col=myscale, pch=19, cex=4)

```

### The format of the rnaqc and bamqc output .txt file is horrible, so transfering data manually (not ideal)

```{r}

qc_stats<-data.frame(matrix(nrow=9,ncol=3))
rownames(qc_stats)<-c("n_mapped_reads",
                      "n_alignments",
                      "n_aligned_genes",
                      "% exonic",
                      "% intronic",
                      "% intergenic",
                      "mapping_quality (%)",
                      "n_mito_human_bases",
                      "n_mito_mouse_bases")

colnames(qc_stats)<-c("unmod_wta","unmod_n1_wta","unmod_n1_tso")

qc_stats$unmod_wta<-c(81218124,129355804,47645441,84.62,10.98,4.39,21.98,211528729,222217746)
qc_stats$unmod_n1_wta<-c(99691114,159348387,56677081,81.06,12.72,6.22,20.08,417991041,267920709)
qc_stats$unmod_n1_tso<-c(37295264,51249515,23759370,84.17,13,2.84,20.99,617298541,448611532)

qc_stats$name<-rownames(qc_stats)

plottable<-melt(qc_stats,id="name")

for (i in unique(plottable$name)){
  p<-ggplot(plottable[plottable$name==i,],aes(x=variable,y=value,fill=variable))+
  geom_bar(stat = "identity")+
  ggtitle(i)+
  theme_bw()+
  rock_roi_theme()+
  theme(legend.position = "none")+
  scale_fill_manual(labels=c("unmod_wta","unmod_n1_wta","unmod_n1_tso"),
                     values=alpha(c(myscale[["unmod"]],myscale[["unmod_n1"]],myscale[["unmod_n1"]]),c(1,1,0.5)))
  
  print(p)
}

```

### Session info

```{r}

sessionInfo()

```


