---
title: "03_first_mixing_experiment_h-mito_coverages.qmd"
author: "Mark Robinson, Izaskun Mallona & Giulia Moro"
format: 
  html:
    toc: true
    embed-resources: true
    keep_md: true
---

### Load packages, load data 

```{r,warning=FALSE, message=FALSE}

rm(list=ls())

library(GenomicRanges)
library(GenomicAlignments)
library(rtracklayer)
library(Gviz)
library(plyranges)
library(seqinr)
library(Rsamtools)
library(googlesheets4)
library(tools)
library(here)
library(GenomicFeatures)
library(khroma)

```

### Setting up knitr 

```{r}

library(knitr)

knitr::opts_chunk$set(fig.width = 2.3,
               fig.height = 2.3,
               fig.align = "center",
               include = TRUE,
               dev = c("png","svg"),
               cache.lazy = FALSE,
               cache=TRUE,
               warning = TRUE,
               message = TRUE)

```

### Loading .gtf files 

```{r}

options(ucscChromosomeNames=FALSE)

gtf_path<-dir(here("00_mixing_experiment"), ".*gtf", 
            recursive = TRUE, full.names = TRUE)

combined_gtf<-rtracklayer::import(gtf_path)

```

### Selection parameters

```{r}

modality<-c("unmod","unmod_n1")

datadir <- dirname(gtf_path)[1]
sce_nd <- readRDS(file.path(datadir, "sce_nd.rds"))

```

### Loading colors

```{r}

myscale<-c(color("muted")(9), gray="darkgrey", 
             black = "black", darkorange = "darkorange",
             yellowgreen = "yellowgreen")

# defining colors for samples and for species

names(myscale) <- c("unmod","unmod_roi","rock","egfp_cds","rockroi","human","unknown","mouse","tdtom_cds","no_detection","doublets","unmod_n1","high")
#plot(1:13, col=myscale, pch=19, cex=4)

```


### Loading .bw files --> the .bam files are too big 

```{r}

getwd()

bw<-dir(here("03_first_mixing_experiment"), "coverage.*bw", 
            recursive = TRUE, full.names = TRUE)

names(bw) <- gsub("_coverage.bw", "", basename(bw))
names(bw) <- gsub("03_first_mixing_", "",names(bw))

datadir <- dirname(bw)[1] # folder where the .bw files are 

coverage<- lapply(bw, function(x) {
    import.bw(x, as="GRanges")
  })

```

### Reading .bed file

```{r}

bed_6 <- unique(as.data.frame(read.table(file.path(datadir,"match_6.bed"),header = FALSE, sep="\t",stringsAsFactors=FALSE, quote="")))
bed_5 <- unique(as.data.frame(read.table(file.path(datadir,"match_5.bed"),header = FALSE, sep="\t",stringsAsFactors=FALSE, quote="")))
bed_4 <- unique(as.data.frame(read.table(file.path(datadir,"match_4.bed"),header = FALSE, sep="\t",stringsAsFactors=FALSE, quote="")))

colnames(bed_6)<-c("chrom","chromStart","chromEnd","strand")
colnames(bed_5)<-c("chrom","chromStart","chromEnd","strand")
colnames(bed_4)<-c("chrom","chromStart","chromEnd","strand")

bed_6<-makeGRangesFromDataFrame(bed_6)
bed_5<-makeGRangesFromDataFrame(bed_5)
bed_4<-makeGRangesFromDataFrame(bed_4)

bed_mouse <- as.data.frame(read.table(file.path(datadir,"mouse_mt.bed"),header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))

colnames(bed_mouse)<-c("chrom","chromStart","chromEnd","strand")
bed_mouse<-makeGRangesFromDataFrame(bed_mouse)

bed_human <- as.data.frame(read.table(file.path(datadir,"human_MT.bed"),header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))

colnames(bed_human)<-c("chrom","chromStart","chromEnd","strand")
bed_human<-makeGRangesFromDataFrame(bed_human)

```

### Generating TxDb gene track

```{r}

track<-makeTxDbFromGFF(file=gtf_path, format="gtf")

```

### Generating tracks for selected genes for mouse

```{r,fig.height=2.3,fig.width=2.3}

#genes_of_interest<-unique(combined_gtf$gene_name[grep("^mt-",combined_gtf$gene_name)])
genes_of_interest<-c("mt-Cytb")

bw_coverages<-list()
gms<-list()

for (x in genes_of_interest){
  sub_gtf<-combined_gtf[grep(x,combined_gtf$gene_name),]
  chr<-unique(as.character(as.data.frame(sub_gtf)$seqnames))
  range<-max(end(ranges(sub_gtf)))-min(start(ranges(sub_gtf)))
  region_start<-min(start(ranges(sub_gtf)))-100 # otherwise for short genes will be too long and opposite for long genes
  region_end<-max(end(ranges(sub_gtf)))+100
  
  print(paste0(x,"_",chr,"_",region_start,"_",region_end))
  
  dtrack <- AnnotationTrack(range=bed_mouse,name="tso")
  dtrack_6 <- AnnotationTrack(range=bed_6,name="tso_6")
  #dtrack_4 <- AnnotationTrack(range=bed_4,name="tso_4")
  #dtrack_5 <- AnnotationTrack(range=bed_5,name="tso_5")
  
  displayPars(dtrack)<-list(shape="box")
  displayPars(dtrack_6)<-list(shape="box")
  #displayPars(dtrack_4)<-list(shape="box")
  #displayPars(dtrack_5)<-list(shape="box")

  gm <- GeneRegionTrack(track,
                           chromosome=chr,
                           name=x,
                           from=region_start,
                           to=region_end,
                           geneSymbol=TRUE,
                           showId=TRUE,
                           transcriptAnnotation="symbol")
  
  displayPars(gm)<-list(col="black",
                           cex.group=0.5,
                           col.line="black",
                           fontcolor.group="black",
                           background.title="darkgrey")
  
  displayPars(gm)<-list(fill="black",
                        shape="arrow")
  
  gms[[x]]<-gm # saving object in case want to replot later
  
  covs_gene<-list()
  for (i in 1:length(coverage)){
    covs_gene[[names(coverage)[[i]]]]<-DataTrack(coverage[[i]],
                     chromosome=chr,
                     from=region_start,
                     to=region_end,
                     name=names(coverage)[[i]])
  }
  
  tso<- grep("tso",names(covs_gene))
  wta<- grep("wta",names(covs_gene))
  
  for (i in tso){
    covs_gene[[i]]@name<-gsub("_tso","",covs_gene[[i]]@name)
    displayPars(covs_gene[[i]])<-list(col.histogram="darkgrey",
                                       fill.histogram="darkgrey",
                                       alpha.title = 1, 
                                       alpha = 0.5)
  }

  for (i in wta){
    covs_gene[[i]]@name<-gsub("_wta","",covs_gene[[i]]@name)
    displayPars(covs_gene[[i]])<-list(col.histogram="black",
                                       fill.histogram="black",
                                       alpha.title = 1, 
                                       alpha = 0.5)
  }

  overlays_bw_gene<-list()
  
  for (i in modality){
    overlays_bw_gene[[i]]<-OverlayTrack(trackList=list(covs_gene[[paste0(i,"_wta")]],covs_gene[[paste0(i,"_tso")]]))

    displayPars(overlays_bw_gene[[i]])<-list(background.title=myscale[[i]])
  }

  ranges<-c()
  for (i in modality){
    ranges[i]<-max(range(c(values(subset(covs_gene[[paste0(i,"_wta")]], from=region_start, to=region_end,chromosome=chr)),
                                     values(subset(covs_gene[[paste0(i,"_tso")]], from=region_start, to=region_end,chromosome=chr)))))
  }

  plotTracks(c(overlays_bw_gene,
               dtrack,
               dtrack_6,
               gm),
          type="histogram",
          from=region_start,
          chromosome=chr,
          to=region_end,
          cex.axis = 0.5,
          cex.title= 1,
          col.axis="white",
          col.title="white",
          col.border.title="white",
          showSampleNames = TRUE,
          lwd.title=0.5,
          ylim=c(0,max(ranges)))
  
    bw_coverages[[x]]<-overlays_bw_gene
}

```

### Generating tracks for selected genes for human

```{r,fig.height=2.3,fig.width=2.3}

#genes_of_interest<-unique(combined_gtf$gene_name[grep("^MT-",combined_gtf$gene_name)])
genes_of_interest<-c("MT-ND5","MT-CO2","MT-ND1")

bw_coverages<-list()
gms<-list()

for (x in genes_of_interest){
  sub_gtf<-combined_gtf[grep(x,combined_gtf$gene_name),]
  chr<-unique(as.character(as.data.frame(sub_gtf)$seqnames))
  range<-max(end(ranges(sub_gtf)))-min(start(ranges(sub_gtf)))
  region_start<-min(start(ranges(sub_gtf)))-100 # otherwise for short genes will be too long and opposite for long genes
  region_end<-max(end(ranges(sub_gtf)))+100
  
  print(paste0(x,"_",chr,"_",region_start,"_",region_end))
  
  dtrack <- AnnotationTrack(range=bed_human,name="tso")
  dtrack_6 <- AnnotationTrack(range=bed_6,name="tso_6")
  #dtrack_4 <- AnnotationTrack(range=bed_4,name="tso_4")
  #dtrack_5 <- AnnotationTrack(range=bed_5,name="tso_5")
  
  displayPars(dtrack)<-list(shape="box")
  displayPars(dtrack_6)<-list(shape="box")
  #displayPars(dtrack_4)<-list(shape="box")
  #displayPars(dtrack_5)<-list(shape="box")

  gm <- GeneRegionTrack(track,
                           chromosome=chr,
                           name=x,
                           from=region_start,
                           to=region_end,
                           geneSymbol=TRUE,
                           showId=TRUE,
                           transcriptAnnotation="symbol")
  
  displayPars(gm)<-list(col="black",
                           cex.group=0.5,
                           col.line="black",
                           fontcolor.group="black",
                           background.title="darkgrey")
  
  displayPars(gm)<-list(fill="black",
                        shape="arrow")
  
  gms[[x]]<-gm # saving object in case want to replot later
  
  covs_gene<-list()
  for (i in 1:length(coverage)){
    covs_gene[[names(coverage)[[i]]]]<-DataTrack(coverage[[i]],
                     chromosome=chr,
                     from=region_start,
                     to=region_end,
                     name=names(coverage)[[i]])
  }
  
  tso<- grep("tso",names(covs_gene))
  wta<- grep("wta",names(covs_gene))
  
  for (i in tso){
    covs_gene[[i]]@name<-gsub("_tso","",covs_gene[[i]]@name)
    displayPars(covs_gene[[i]])<-list(col.histogram="darkgrey",
                                       fill.histogram="darkgrey",
                                       alpha.title = 1, 
                                       alpha = 0.5)
  }

  for (i in wta){
    covs_gene[[i]]@name<-gsub("_wta","",covs_gene[[i]]@name)
    displayPars(covs_gene[[i]])<-list(col.histogram="black",
                                       fill.histogram="black",
                                       alpha.title = 1, 
                                       alpha = 0.5)
  }

  overlays_bw_gene<-list()
  
  for (i in modality){
    overlays_bw_gene[[i]]<-OverlayTrack(trackList=list(covs_gene[[paste0(i,"_wta")]],covs_gene[[paste0(i,"_tso")]]))

    displayPars(overlays_bw_gene[[i]])<-list(background.title=myscale[[i]])
  }

  ranges<-c()
  for (i in modality){
    ranges[i]<-max(range(c(values(subset(covs_gene[[paste0(i,"_wta")]], from=region_start, to=region_end,chromosome=chr)),
                                     values(subset(covs_gene[[paste0(i,"_tso")]], from=region_start, to=region_end,chromosome=chr)))))
  }

  plotTracks(c(overlays_bw_gene,
               dtrack,
               dtrack_6,
               #dtrack_5,
               #dtrack_4,
               gm),
          type="histogram",
          from=region_start,
          chromosome=chr,
          to=region_end,
          cex.axis = 0.5,
          cex.title= 1,
          col.axis="white",
          col.title="white",
          col.border.title="white",
          showSampleNames = TRUE,
          lwd.title=0.5,
          ylim=c(0,max(ranges)))
  
    bw_coverages[[x]]<-overlays_bw_gene
}

```

### Session info

```{r}

sessionInfo()

```
