---
title: "Read in junctions tables, store in RDS"
format:
  html:
    toc: true
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

## Load packages, load data

```{r, warning=FALSE, message=FALSE}
library(SingleCellExperiment)
library(ggplot2)
library(dplyr)
library(pheatmap)
library(here)
library(tibble)
library(khroma)
library(googlesheets4)
library(tidyr)
library(reshape2)
library(readr)
library(Matrix)
library(rtracklayer)
library(Gviz)

datadir <- file.path(here("01_pdgfra_experiment"), "data")

# read filtered-clustered object to SCE
sce <- readRDS(file.path(datadir,
                         "sce_qc-filtered-nodoublets-clustered-annotated.rds"))

myscale <- c(color("muted")(9), gray="lightgray", 
             black = "black", darkorange = "darkorange",
             yellowgreen = "yellowgreen")
names(myscale) <- as.character(1:13)

plot(1:13, col=myscale, pch=19, cex=4)

inds <- split(seq_len(ncol(sce)), sce$annotation)
names(myscale) <- levels(factor(sce$annotation))
ann_colors = list(annotation = myscale[seq_len(length(inds))])


uct <- unique(sce$annotation)
names(uct) <- uct
uct[grepl("Crypt_bottom", uct)] <- "Crypt_bottom"
uct[!grepl("Crypt", uct)] <- "Epithelial"

sce$celltype <- uct[sce$annotation] 


# write files of barcodes -- to be used later with `samtools`
ss <- strsplit(rownames(colData(sce)), ".", fixed=TRUE)

df <- data.frame(sample_celltype = paste0(sce$sample_id, "__",
                                          sce$celltype),
                 barcode = sapply(ss, .subset2, 2))

dfs <- split(df[,-1,drop=FALSE], df$sample_celltype)
for(i in 1:length(dfs)) {
  fo <- file.path(datadir, paste0(names(dfs)[i],".barcode"))
  writeLines(dfs[[i]]$barcode, con = fo)
}

dir(datadir, ".barcode$")


```


## Read in junction counts to sparse matrix


```{r}

# juncfs <- list.files(file.path(datadir, "junctions"),
#                      ".featurecounts$", recursive = TRUE,
#                      full.names = TRUE)
# 
# barcode <- sapply(basename(juncfs) %>% strsplit("CB_"),
#                   function(u) gsub(".bam.featurecounts","", u[2]))
# 
# samp <- sapply(juncfs %>% dirname %>% basename %>% strsplit("___"),
#        .subset, 1)
# 
# key <- paste0(samp, ".", barcode)
# 
# length(setdiff(sce$sample_id.barcode, key))
# length(setdiff(key, sce$sample_id.barcode))
# 
# # only keep junction counts for barcodes we still have
# keep <- key %in% sce$sample_id.barcode
# juncfs <- juncfs[keep]
# key <- key[keep]
# 
# # manually construct sparse matrix
# col_num <- match(key, sce$sample_id.barcode)
# 
# feat_tab <- read_delim(juncfs[1], delim = "\t", skip = 1,
#                        col_types = "ccddcdd") %>% 
#   as.data.frame %>% select(Geneid,Chr,Start,End,Strand,Length)
# 
# system.time(
# cnts_tab <- sapply(juncfs %>% setNames(key), 
#                    function(u) {
#   rd <- read_delim(u, delim = "\t", skip = 1,
#                    col_types = "ccddcdd")
#   rd[,ncol(rd), drop = TRUE]
# })
# )
# 
# w <- cnts_tab > 0
# rows <- row(cnts_tab)[w]
# cols <- col_num[col(cnts_tab)[w]]
# 
# cnts_sparse <- sparseMatrix(rows, cols, x=cnts_tab[w],
#                             dims = c(nrow(feat_tab), ncol(sce)) )
 

## Read in junctions counts to sparse matrix


juncfs <- list.files(file.path(datadir, "junctions"),
                     "featurecounts.jcounts$", recursive = TRUE,
                     full.names = TRUE)

barcode <- sapply(basename(juncfs) %>% strsplit("CB_"),
                  function(u) gsub(".bam.featurecounts.jcounts","", u[2]))

samp <- sapply(juncfs %>% dirname %>% basename %>% strsplit("___"),
       .subset, 1)

key <- paste0(samp, ".", barcode)
head(key)

length(setdiff(sce$sample_id.barcode, key))
length(setdiff(key, sce$sample_id.barcode))

# only keep junction counts for barcodes we still have
keep <- key %in% sce$sample_id.barcode
juncfs <- juncfs[keep]
key <- key[keep]

# manually construct sparse matrix
col_num <- match(key, sce$sample_id.barcode)

fi <- file.info(juncfs)

# (base) mark@MLS-M-MARO rock_roi_paper % more /Users/mark/projects/scrnaseq/rock_roi_paper/01_pdgfra_experiment/data/junctions/pdgfra_rockroi_multimodal___2024-02-14_12:27:28/split_.TAG_CB_GTGTTCCAG_GTGCTCGTT_TTGGAATCA.bam.featurecounts.jcounts
# PrimaryGene     SecondaryGenes  Site1_chr       Site1_location  Site1_strand    Site2_chr       Site2_location  Site2_strand    pdgfra_rockroi_multimodal___2024-02-14_12:27:28/split_.TAG_CB_GTGTTCCAG_GTGCTCGTT_TTGGAATCA.bam
# NA      NA      chr5    74918480        NA      chr5    75183109        NA      1
# roi_5   NA      chr5    75167967        NA      chr5    75170495        NA      1
# roi_6   NA      chr5    75170666        NA      chr5    75170762        NA      1
# NA      NA      chr5    75170951        NA      chr5    75173389        NA      1
# NA      NA      chr5    75175071        NA      chr5    75176667        NA      2
# roi_16  NA      chr5    75183142        NA      chr5    75185514        NA      4

read_junc_file <- function(f) {
  read_delim(f, delim = "\t", skip = 1,
                       col_types = "ccciccici", 
                       col_names = c("PrimaryGene","SecondaryGenes",
                                     "Site1_chr","Site1_location","Site1_strand",
                                     "Site2_chr","Site2_location","Site2_strand",
                                     "count")) %>% 
    mutate(region = paste0(ifelse(is.na(PrimaryGene),"",
                                  paste0("[",PrimaryGene,"] ")),
                           Site1_chr,":",Site1_location,"-",Site2_location)) %>%
    select(region,count)
    
}

(feat_tab <- read_junc_file(juncfs[which.max(fi$size)]))

system.time(
cnts_tab <- lapply(juncfs %>% setNames(key),
                   read_junc_file) 
) 

cnts_df <- data.frame(barcode = rep(names(cnts_tab), 
                                    sapply(cnts_tab, nrow)),
                      bind_rows(cnts_tab))

# make into table                    
tab <- dcast(cnts_df, region ~ barcode, 
             value.var = "count") %>% as_tibble %>%
  column_to_rownames("region") %>% as.matrix
tab[is.na(tab)] <- 0


cnts_df %>% group_by(region) %>% 
  tally(wt = count) %>% 
  arrange(desc(n)) %>% print(n=20)

m <- match(colnames(tab), sce$sample_id.barcode)
w <- tab > 0
rows <- row(tab)[w]
cols <- m[col(tab)[w]]

cnts_sparse <- sparseMatrix(rows, cols, x=tab[w],
                            dims = c(nrow(tab), ncol(sce)) )

rd <- DataFrame(region = rownames(tab))
ss <- strsplit(rd$region, ":", fixed = TRUE)
ss2 <- sapply(ss, function(u) strsplit(u[2], "-", fixed = TRUE))

rd$start <- sapply(ss2, .subset2, 1)
rd$end <- sapply(ss2, .subset2, 2)
rd$region_name <- sapply(ss, .subset2, 1)

se <- SummarizedExperiment(assays = list(tso_junction = cnts_sparse),
                           rowData = rd,colData = colData(sce))
```

## Reorganize data into long format

```{r}


b <- apply(cnts_sparse, 1, function(u) {
  table(u>0, sce$celltype, sce$sample_id) %>% 
    as.data.frame %>%
    setNames(c("expressed","celltype","sample","freq")) %>%
    group_by(celltype, sample) %>%
    summarise(perc_expressed = 100*weighted.mean(expressed==TRUE, freq)) %>%
    ungroup
  }, simplify = FALSE) %>%
  setNames(rownames(tab)) 

for(i in 1:length(b)) b[[i]]$region <- names(b)[i]

b <- b %>% bind_rows %>% left_join(rd %>% as.data.frame)
  


```

## Save R objects to disk

```{r}
saveRDS(b, file = file.path(datadir, "junctions", "df-annotated-junctions.rds"))
saveRDS(se, file = file.path(datadir, "junctions", "se-annotated-junctions.rds"))

```


## `sessionInfo()`

```{r}
sessionInfo()
```

