---
title: "Preprocessing of 01_pdgfra_experiment"
format:
  html:
    toc: true
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

## Load packages, load data

```{r, warning=FALSE, message=FALSE}
library(SingleCellExperiment)
library(scran)
library(ggplot2)
library(dplyr)
library(scater)
library(reshape2)
library(UpSetR)
library(limma)
library(cowplot)
library(pheatmap)
library(readr)
library(plotROC)
library(here)

rdss <- dir(here("01_pdgfra_experiment"), "^pd.*rds$", 
            recursive = TRUE, full.names = TRUE)
names(rdss) <- gsub("_sce.rds", "", basename(rdss))
rdss <- rdss[!grepl("bak", rdss)] # remove those in 'bak' dir
rdss <- rdss[names(rdss) != "pdgfra_rockroi_unimodal"]
rdss

datadir <- dirname(rdss)[1]

sces <- mapply(function(u,v)  {
  rds <- readRDS(u)
  rds$sample_id <- v
  rds$sample_id.barcode <- paste0(v,".",colnames(rds))
  colnames(rowData(rds)) <- c("name", "type", "value")
  g <- grepl("^ENS", rownames(rds))
  rownames(rds)[g] <- paste0(rownames(rds)[g], 
                             "__", rowData(rds)$name[g])
  rowData(rds)$gene_type <- "capture"
  k <- grepl("^ENSMUS", rownames(rds))
  rowData(rds)$gene_type[k] <- "mouse_gene"
  k <- grepl("^mt", rowData(rds)$name)
  rowData(rds)$gene_type[k] <- "mouse_mito"
  k <- grepl("roi", rowData(rds)$name)
  rowData(rds)$gene_type[k] <- "capture"
  k <- grepl("capture", rowData(rds)$name)
  rowData(rds)$gene_type[k] <- "capture"
  rds
}, rdss, names(rdss))

sce <- Reduce(cbind, sces)
```


## Do some QC things (on WTA)

```{r}

rowData(sce)$gene_type %>% table

rd <- rowData(sce)
sce <- addPerCellQCMetrics(sce, assay.type = "wta",
                           subsets=list(capture=rd$gene_type=="capture",
                                        mouse_gene=rd$gene_type=="mouse_gene",
                                        mouse_mito=rd$gene_type=="mouse_mito"))

cd <- colData(sce) %>% as.data.frame

ggplot(cd, aes(x = total,
               y = detected,
               colour = subsets_mouse_mito_percent)) +
  geom_point() +
  scale_x_log10() + scale_y_log10() +
  geom_density_2d(colour = "orange") +
  facet_wrap(~sample_id)

ggplot(cd, aes(x = total, y = subsets_mouse_mito_percent)) +
  geom_point() + scale_x_log10() + scale_y_sqrt() +
  facet_wrap(~sample_id) + 
  geom_hline(yintercept=c(1,30), colour="orange") +
  geom_vline(xintercept=c(2000), colour="orange") +
  geom_density2d()

ggplot(cd, aes(x = detected, y = subsets_mouse_mito_percent)) +
  geom_point() + scale_x_log10() + scale_y_sqrt() +
  facet_wrap(~sample_id) + 
  geom_hline(yintercept=c(1,75), colour="orange") +
  geom_vline(xintercept=c(800), colour="orange") +
  geom_density2d()


# crude filter
dim(sce)
mito <- sce$subsets_mouse_mito_percent
sces <- sce[,sce$detected>800 & mito>1 & mito<75]
# sces <- sces[rowSums(assay(sces,1))>2 ,]  # don't b/c removes from off/on target mtx
sces <- sces[rowSums(assay(sces,1))>2 | rowData(sces)$gene_type=="capture" ,] 
dim(sces)


# save filtered to RDS
saveRDS(sces, file.path(datadir, "sce_qc-filtered.rds"))

# remove extra things
rm(cd, sce); gc()

```

## From filtered set, look at TSOs

```{r}

rowData(sces) %>% as.data.frame %>% tail(10)

# df <- data.frame(sample_id = sces$sample_id,
#                  rock_egfp_wta = assay(sces, "wta")["roi_egfp",],
#                  rock_egfp_tso = assay(sces, "tso_off_and_ontarget_unique")["roi_egfp",],
#                  subsets_mouse_gene_percent = sces$subsets_mouse_gene_percent)
# 
# ggplot(df, aes(sample_id, rock_egfp_wta, 
#                colour=subsets_mouse_gene_percent)) +
#   geom_jitter()
# 
# ggplot(df, aes(sample_id, rock_egfp_tso, 
#                colour=subsets_mouse_gene_percent)) +
#   geom_jitter()

# z <- assay(altExp(sces),1)
# rn <- rownames(z)
# assay(altExp(sces),1)[intersect(rn, rownames(sces)),1:20]
# assay(sces, 2)[intersect(rn, rownames(sces)),1:20]

# plotExpression(sces, features="rock_egfp", 
#                x="sample_id", exprs_values="wta") + ggtitle("wta")

# plotExpression(sces, features="rock_egfp", 
#                x="sample_id", exprs_values="tso_off_and_ontarget_unique",
#                colour_by = "subsets_mouse_gene_percent", point_size = 0) +
#   ggtitle("tso")

rds <- rowData(sces)
tso_qc <- perCellQCMetrics(sces, assay.type = "tso_off_and_ontarget_unique",
                           subsets=list(capture=rds$gene_type=="capture",
                                        mouse_gene=rds$gene_type=="mouse_gene",
                                        mouse_mito=rds$gene_type=="mouse_mito"))

all(rownames(tso_qc)==colnames(sces))

df <- data.frame(tso_total = tso_qc$total,
                 tso_capture_sum = tso_qc$subsets_capture_sum,
                 tso_mito_percent = tso_qc$subsets_mouse_mito_percent,
                 wta_total = sces$total,
                 wta_capture_sum = sces$subsets_capture_sum,
                 wta_mito_percent = sces$subsets_mouse_mito_percent,
                 sample_id = sces$sample_id)

ggplot(df, aes(x = tso_total, y = wta_total)) +
  geom_point() +
  scale_x_log10() + scale_y_log10() +
  facet_wrap(~sample_id, ncol = 1)

ggplot(df, aes(x = tso_capture_sum, y = wta_capture_sum)) +
  geom_jitter(height = .2) +
  # scale_x_log10() + scale_y_log10() +
  facet_wrap(~sample_id)

ggplot(df, aes(x = tso_mito_percent, y = wta_mito_percent)) +
  geom_point() +
  # scale_x_log10() + scale_y_log10() +
  facet_wrap(~sample_id) +
  geom_abline(intercept = 0, slope = 1)

ggplot(df, aes(x = tso_total, y = tso_mito_percent)) +
  geom_point(size = .3) +
  scale_x_sqrt() +
  scale_y_sqrt() +
  # geom_density2d() +
  facet_wrap(~sample_id)
```


## Selected TSOs by mouse/human expression

```{r}

(rn <- rownames(altExp(sces)))

exprs <- assay(altExp(sces),1)

sort(rowSums(exprs, na.rm = TRUE), decreasing = TRUE) -> sorted

par(mfrow=c(2,3))
for(tso in names(sorted))
  smoothScatter(sces$subsets_mouse_mito_percent,
             jitter(exprs[tso,]), pch=19, main=tso,
       xlab="mouse percent",
       ylab=tso)


```


## sessionInfo()

```{r}



```

