---
title: "Preprocessing of 01_mixing_experiment (Mouse with egfr, Human with tdtomato)"
format:
  html:
    toc: true
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

## Load packages, load data

```{r, warning=FALSE, message=FALSE}
library(SingleCellExperiment)
library(scran)
library(scater)
library(ggplot2)
library(dplyr)
library(reshape2)
library(UpSetR)
library(limma)
library(cowplot)
library(pheatmap)
library(readr)
library(plotROC)
library(here)


datadir <- file.path(here("01_pdgfra_experiment"), "data")

# save filtered to RDS
sces <- readRDS(file.path(datadir, "sce_qc-filtered.rds"))

```


## Normalize, HVGs


```{r}

sces <- logNormCounts(sces, assay.type = "wta")

# find HVGs
mgv <- modelGeneVar(sces, block = sces$sample_id)

mgv_pb  <- lapply(mgv$per.block, function(u) {
 o <- order(u$p.value)
 u <- u[o,]
 head(rownames(u), 1000)
})

# most are sample-wise (?)
upset(fromList(mgv_pb))

# arbitrary cutoff to pick some HVGs
hvg <- mgv$bio > .01 & mgv$p.value < .01 & mgv$mean > .2
mgv[hvg,] %>% 
  as.data.frame %>% rownames -> hvg
length(hvg)

all(rownames(sces)==rownames(mgv))

mgv <- cbind(mgv, gene_type = rowData(sces)$gene_type)

rowData(sces)[hvg,]$gene_type %>% table
# basically all expressed mouse genes are HV; mainly different b/w
# +ROI and -ROI

# remove mito genes
hvg <- mgv$bio > .01 & mgv$p.value < .01 & mgv$mean > .2 & mgv$gene_type=="mouse_gene"
rn <- rownames(mgv)[hvg]
length(rn)


ggplot(mgv %>% data.frame %>% filter(gene_type != "capture"),
       aes(x=mean, y=bio, colour=p.value<.05, shape = gene_type)) +
  geom_point() + facet_wrap(~gene_type)

```


## Dim reduction, UMAP

```{r}

sces <- fixedPCA(sces, subset.row=rn, rank = 30) 
sces <- runUMAP(sces, dimred="PCA")

# km <- kmeans(reducedDim(sces, "UMAP"), centers = 5)

# plotPCA(sces, colour_by = "sample_id", ncomponents = 4)
# plotPCA(sces, colour_by = "subsets_human_gene_percent", 
#         ncomponents = 4)

plotUMAP(sces, colour_by = "sample_id") + facet_wrap(~colour_by)
plotUMAP(sces, colour_by = "total", shape_by = "sample_id") + facet_wrap(~shape_by)

# very crude but works
# set.seed(1976)
# km <- kmeans(reducedDim(sces, "UMAP"), centers = 3, iter.max = 100)


nn.clusters <- clusterCells(sces, use.dimred="PCA")
table(nn.clusters)

nn.clusters <- clusterCells(sces, use.dimred="PCA",
                            BLUSPARAM=NNGraphParam(k=30))
sces$cluster <- nn.clusters

plotUMAP(sces, colour_by="cluster", shape_by = "sample_id",
         point_size = 4, point_alpha = .9) + 
  facet_wrap(~shape_by)

table(sces$sample_id, sces$cluster)

# logcounts <- as.matrix(logcounts(sces))
mm <- model.matrix(~cluster, 
                   data=as.data.frame(colData(sces)))

# inds <- split(1:ncol(sces), sces$cluster)
# s <- unlist(lapply(inds, sample, 1000))
# 
# s1 <- unlist(lapply(inds, sample, 50))
lcounts <- logcounts(sces)
# corr <- cor( as.matrix(lcounts[,s1]) )
# col_anno <- colData(sces)[s1,c("origin","sample_id")] %>% as.data.frame
# pheatmap(corr, show_rownames = FALSE, show_colnames = FALSE,
#          treeheight_row = 0, treeheight_col = 0,
#          annotation_col = col_anno)

table(rs <- rowSums(lcounts)>50 & rowData(sces)$gene_type == "mouse_gene" )
f <- lmFit(as.matrix(lcounts[rs,]), mm)
f <- eBayes(f)

topTable(f, coef=2:10, number = 10)
tt <- topTable(f, coef=2:10, number = 1e6, sort.by = "none")


# plotUMAP(sces, colour_by = "ENSMUSG00000025903.14__Lypla1")
# plotUMAP(sces, colour_by = "ENSMUSG00000026193.15__Fn1")

aac <- aggregateAcrossCells(sces, sces$cluster,use.assay.type="wta")


calc_entropy <- function(u) {
  p <- u[u>0]
  p <- p/sum(p)
  -sum(p*log(p))
}

# adjust the aggregated counts for the number of cells
agg_counts <- assay(aac,"wta")[rs,]
for(i in 1:ncol(agg_counts))
  agg_counts[,i] <- agg_counts[,i]/sum(agg_counts[,i])*1e6

ents <- apply(agg_counts, 1, calc_entropy)

# gs <- rownames(tt)[tt$F > 50 & ents < 1.35]
gs <- rownames(tt)[tt$F > 100 & ents < 1]

plot(ents, tt$F, log="y")

df <- data.frame(gene = names(ents), 
                 entropy=ents, Fstat=tt$F,
                 cluster.max = apply(agg_counts, 1, which.max)) %>%
  mutate(order_by = Fstat / entropy) %>%
  filter(Fstat > 400, entropy < 1.2) %>%
  arrange(desc(order_by)) %>%
  group_by(cluster.max) %>% slice_max(order_by = order_by, n = 10)

col_anno <- colData(sces)[,c("sample_id","cluster")] %>% as.data.frame

# o <- order(sces$cluster)

inds <- split(seq_len(ncol(sces)), sces$cluster)
inds <- lapply(inds, sample, 150, replace = FALSE)

# manually put clusters in order
cluster_order <- c(4,8,10,6,1,3,7,5,2,9)
inds <- inds[cluster_order]

co <- unlist(inds)

genes <- split(df$gene, df$cluster.max)
genes <- genes[cluster_order] %>% unlist

pheatmap(lcounts[genes,co], show_rownames = TRUE,
         show_colnames = FALSE, scale="none",
         annotation_col = col_anno[co,],
         cluster_rows = FALSE,
         cluster_cols = FALSE, fontsize_row = 8)


pheatmap(lcounts[genes,co], show_rownames = TRUE,
         show_colnames = FALSE, scale="none",
         annotation_col = col_anno[co,],
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         cluster_rows = TRUE,
         cluster_cols = TRUE, fontsize_row = 8)



# col_anno <- data.frame(cluster = rep( names(inds), sapply(inds, length)


plotUMAP(sces, colour_by = "ENSMUSG00000016494.9__Cd34")
plotUMAP(sces, colour_by = "ENSMUSG00000028255.6__Clca1")

# plotUMAP(sces, colour_by = "ENSMUSG00000026701.15__Prdx6")
# 	
# plotUMAP(sces, colour_by = "ENSMUSG00000049350.6__Zg16")
# plotUMAP(sces, colour_by = "ENSMUSG00000015354.8__Pcolce2")
# 
# plotUMAP(sces, colour_by = "ENSMUSG00000033740.17__St18")
# 
# plotExpression(sces, x = "cluster", 
#                features = "ENSMUSG00000033740.17__St18")



```



## Focus on mouse

```{r}

m <- sces[rowData(sces)$gene_type=="mouse_gene", 
             sces$subsets_mouse_gene_percent > 50]
table(k <- rowSums(assay(m,"wta")) > 0)
m <- m[k,]

length(unique(colnames(m)))

table(m$sample_id)


mgv <- modelGeneVar(m, block = m$sample_id)

# not much overlap across 'treatment', but that's probably
# expected because there are no cell types here
mgv_pb  <- lapply(mgv$per.block, function(u) {
 o <- order(u$p.value)
 u <- u[o,]
 head(rownames(u), 500)
})
upset(fromList(mgv_pb))


ggplot(mgv %>% data.frame,
       aes(x=mean, y=bio, colour=p.value<.05)) +
  geom_point()

hvg <- mgv$bio > .005 & mgv$p.value < .1
table(hvg)
rn <- rownames(mgv)[hvg]

m <- fixedPCA(m, subset.row=rn) 
m <- runUMAP(m, dimred="PCA")

# plotPCA(ms, colour_by = "mod", ncomponents = 4)
plotUMAP(m, colour_by = "sample_id", point_size = 4)
# plotUMAP(m, colour_by = "sample_id") + facet_wrap(~colour_by)


logcounts <- as.matrix(logcounts(m))
mm <- model.matrix(~sample_id, data=as.data.frame(colData(m)))

f <- lmFit(logcounts, mm)
f <- eBayes(f)

tt <- topTable(f, coef=2:4, number = 1e6, sort.by = "none")


inds <- split(1:ncol(m), m$sample_id)
s <- unname(unlist(lapply(inds, sample, 200)))


aac <- aggregateAcrossCells(m, m$sample_id,use.assay.type="wta")


calc_entropy <- function(u) {
  p <- u[u>0]
  p <- p/sum(p)
  -sum(p*log(p))
}

# adjust the aggregated counts for the number of cells
agg_counts <- assay(aac,"wta")
# tb_tis <- table(hs$mod)
# all( colnames(agg_counts)==names(tb_tis) )
# 
# for(i in 1:ncol(agg_counts))
#   agg_counts[,i] <- agg_counts[,i]/tb_tis[i]
for(i in 1:ncol(agg_counts))
  agg_counts[,i] <- agg_counts[,i]/sum(agg_counts[,i])*1e6

ents <- apply(agg_counts, 1, calc_entropy)

gs <- rownames(tt)[tt$F > 50 & ents < 1.35]
# gs <- rownames(tt)[tt$F > 100 & ents < 1.3]

plot(ents, tt$F, log="y")


col_anno <- colData(sces)[,c("sample_id","cluster")] %>% as.data.frame

o <- order(sces$cluster)
pheatmap(lcounts[gs,o], show_rownames = TRUE, 
         show_colnames = FALSE, scale="row",
         annotation_col = col_anno,
         cluster_cols = FALSE,
         fontsize_row = 8)




# for(i in 1:nrow(logcounts)) {
#   mn <- min(logcounts[i,])
#   mx <- max(logcounts[i,])
#   logcounts[i,] <- (logcounts[i,]-mn)/(mx-mn)
# }

col_anno <- colData(m)[,c("sample_id","origin")] %>% as.data.frame

pdf("mouse_heatmap_plus-minus-roi.pdf", height=15, width=8)
pheatmap(logcounts[gs,s], show_rownames = TRUE, 
         show_colnames = FALSE, scale="none",
         annotation_col = col_anno[s,],
         cluster_cols = FALSE,
         fontsize_row = 8)
dev.off()


# plotExpression(m, features=rownames(head(tt[o,])),
#                x= "sample_id", colour_by = "sample_id")

# plotExpression(ms, features=c("Gm11599_ENSMUSG00000084333.1",
#                               "Commd7_ENSMUSG00000056941.17"),
#                x= "mod",
#                colour_by = "mod")
# 
# plotUMAP(ms, colour_by="TRAPPC3_ENSG00000054116.12",
#                shape_by= "mod")


```

## Explore `fuzznuc`


```{r}

gene_info <- read_tsv(file.path(datadir,
                                "genes_vs_fuzznuc_mixing.txt.gz"), 
                      col_names = c("ids", "pattern", "mismatches"))
table(gene_info$pattern, gene_info$mismatches)


extract_stuff <- function(u, term = "gene_type", default = "unknown") {
  g <- grep(term, u, value=TRUE)
  if(length(g)==0)
    return(default)
  else
    return(g)
}


ss <- strsplit(gene_info$ids, ";", fixed = TRUE)
gene_info$g_id <- gsub('\"$',"",
                       gsub('gene_id \"', '', sapply(ss, .subset, 1)))
gene_info$tr_id <- gsub('\"$',"",
                        gsub(' transcript_id \"', '', sapply(ss, .subset, 2)))
gene_info$gene_name <- gsub('\"$',"",
                  gsub(' gene_name \"', '',
                       sapply(ss, extract_stuff, term = "gene_name", default = "")))
gene_info$gene_type <- gsub('\"$',"",
                  gsub(' gene_type \"', '',
                       sapply(ss, extract_stuff, term = "gene_type")))


gene_info$id <- paste0(gene_info$g_id, "__", gene_info$gene_name)
unk <- gene_info$gene_type=="unknown"
gene_info$id[unk] <- gene_info$tr_id[unk]
gene_info$id <- gsub("^ROI", "roi", gene_info$id)

# gene_info$ids <- NULL
# gene_info$id <- 


common_genes <- intersect(gene_info$id, rownames(rowanno))

rowanno <- data.frame(match = rep("nomatch", nrow(logcounts)),
                      row.names = rownames(logcounts))

m1 <- match(common_genes, rownames(rowanno))
m2 <- match(common_genes, gene_info$id)

# rowanno[head(m1),,drop=FALSE]
# gene_info[head(m2),-c(1:4)]

rowanno$match[m1] <- gene_info$mismatches[m2]

ann_colors = list(
    origin = c(mouse = "salmon", human = "firebrick"),
    match = c(nomatch = "grey", `.` = "black", `1` = "red", `2` = "orange"),
    sample_id = c(mixing_rock = "#7570B3", 
                  mixing_rockroi = "#E7298A",
                  mixing_unmod = "#66A61E", 
                  mixing_unmod_roi = "orange")
)


pheatmap(logcounts[gs,s], show_rownames = TRUE, 
         show_colnames = FALSE, scale="none",
         annotation_col = col_anno[s,],
         annotation_row = rowanno[gs,,drop=FALSE],
         annotation_colors = ann_colors,
         cluster_cols = FALSE,
         fontsize_row = 8)


diff <- (f$coef[,1]+f$coef[,3])-f$coef[,2]

par(mfrow=c(1,2))
boxplot(diff ~ rowanno$match, ylab="+ROI - -ROI")
boxplot(diff ~ rowanno$match, ylim=c(-1,1), ylab="+ROI - -ROI")

# vioplot(diff ~ rowanno$match)
# vioplot(diff ~ rowanno$match, ylim=c(-1,1))

```

