---
title: "05_FACS_plots_j_storage"
author: "Giulia Moro"
format: 
  html:
    toc: true
    embed-resources: true
    keep_md: true
---

### Load packages

```{r,warning=FALSE, message=FALSE}

rm(list=ls())

library(flowCore)
library(khroma)
library(here)
library(flowViz)
library(ggcyto)
library(ggplot2)
library(ggridges)
library(ggh4x)
library(reshape2)

```

### Setting up knitr 

```{r}

knitr::opts_chunk$set(fig.width = 2.7,
               fig.height = 2.7,
               fig.align = "center",
               include = TRUE,
               dev = c("png","svg"),
               cache=TRUE,
               cache.lazy = FALSE,
               warning = TRUE,
               message = TRUE)

```

### Themes

```{r}

rock_roi_theme<-function(){
  theme(axis.text = element_text(size=5), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        legend.title=element_text(size=7,face="bold"),
        legend.text=element_text(size=5),
        aspect.ratio=1,
        legend.key.size = unit(0.5, 'cm'),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
}

facs_rock_roi_theme_multiple_panels<-function(){
    theme(axis.text = element_text(size=5), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        legend.key.size = unit(0.5, 'cm'),
        legend.title=element_text(size=7,face="bold"),
        legend.text=element_text(size=5),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.border = element_rect(colour = "black", fill = NA))
}

facs_hist_rock_roi_theme<-function(){
  theme(axis.text = element_text(size=5), 
        plot.title=element_text(size=7,face="bold",hjust=0.5),
        axis.title=element_text(size=7,face="bold"),
        strip.text=element_text(size=7,face="bold"),
        legend.title=element_text(size=7,face="bold"),
        legend.text=element_text(size=5),
        aspect.ratio=1,
        legend.key.size = unit(0.5, 'cm'),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5),
        legend.title.align=0.5,
        panel.border=element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background=element_rect(colour="white", 
                                               fill="white"))
}

```


### Importing data

```{r}

rdss1 <- dir(here("05_facs_plots/data/v2_storage_first"), "*.fcs", 
            recursive = TRUE, full.names = TRUE)
datadir <- dirname(rdss1)[1] # folder where the .rds files are 

rdss2 <- dir(here("05_facs_plots/data/v2_storage_second"), "*.fcs", 
            recursive = TRUE, full.names = TRUE)
datadir <- dirname(rdss2)[1] # folder where the .rds files are

```

### Reading data

```{r}

storage_1<-read.flowSet(rdss1)

sampleNames(storage_1) <- gsub("Specimen_001_", "", sampleNames(storage_1))
sampleNames(storage_1) <- gsub(".fcs", "", sampleNames(storage_1))

# reordering data

storage_1<-storage_1[c(2,1)]

sampleNames(storage_1)<-c("19_100_gfp","19_10_gfp")
pData(storage_1)$name<-c("19_100_gfp","19_10_gfp")

```

### Defining colors

```{r}

myscale<-c(color("muted")(9), gray="darkgrey", 
             black = "black", darkorange = "darkorange",
             yellowgreen = "yellowgreen")

# defining colors for samples and for species

names(myscale) <- c("unmod","unmod_roi","rock","egfp_cds","rockroi","human","unknown","mouse","tdtom_cds","no_detection","doublets","low","high")

#plot(1:13, col=myscale, pch=19, cex=4)

```

### Gate

```{r,fig.width=8,fig.height=5}

sqrcut <- matrix(c(50000,60000,70000,80000,90000,100000,110000,100000,90000,80000,70000,60000,50000,
                   40000,65000,70000,75000,75000,60000,50000,25000,20000,18000,20000,25000,40000),ncol=2,nrow=13)

colnames(sqrcut) <- c("FSC-A","SSC-A")

beads <- polygonGate(filterId="beads", gate= sqrcut)

ggcyto(storage_1, aes(x = FSC.A, y = SSC.A)) + 
  geom_hex(bins = 100) + 
  facet_wrap(~factor(name, levels = c("19_100_gfp","19_10_gfp"))) +
  geom_gate(beads) + 
  geom_stats(type = c("percent"),size = 2,adjust=c(0.7,1.2)) +
  theme_bw() +
  facs_rock_roi_theme_multiple_panels() 

gs <- GatingSet(storage_1) # create a GatingSet
gs_pop_add(gs, beads,parent="root")
recompute(gs)

# check filtering 

filt_titration <- Subset(storage_1, beads)

ggcyto(filt_titration, aes(x = FSC.A, y = SSC.A)) + 
  geom_hex(bins = 100) + 
  facet_wrap(~factor(name, levels = c("19_100_gfp","19_10_gfp"))) +
  geom_gate(beads) + 
  theme_bw() +
  facs_rock_roi_theme_multiple_panels()

```

### Trasformation data biexponential

```{r,fig.width=3,fig.height=5.4}

ggcyto(filt_titration, aes(x = "APC-A", fill = name,color=name)) + 
  geom_histogram(alpha = 1,bins=256) + 
  scale_x_flowjo_biexp() +
  facet_wrap(~factor(name, levels = c("19_100_gfp","19_10_gfp")),ncol=1,switch = "y")+
  theme_bw() +
  facs_hist_rock_roi_theme()+
  theme(strip.placement = "outside")+
  theme(legend.position = "none")+
  theme(strip.text = element_text(size=5,face="bold"))+
  force_panelsizes(rows = unit(0.25, "in"),
                   cols = unit(2.5, "in"))+
  theme(panel.spacing = unit(0.1, "lines"))+
  theme(strip.text.y = element_blank())+
  theme(axis.line = element_line())+
  scale_fill_manual(values=c("19_100_gfp"="#12783D",
                             "19_10_gfp"="#99CA3E"))+
    scale_color_manual(values=c("19_100_gfp"="#12783D",
                             "19_10_gfp"="#99CA3E"))
  
```

### Boxplots

```{r,fig.width=8.1,fig.height=2.7}

list_filt_titration<-list()

for (i in 1:length(filt_titration)){
  list_filt_titration[[sampleNames(filt_titration)[[i]]]]<-as.data.frame(filt_titration[[i]]@exprs)$"APC-A"
}

plottable<-melt(list_filt_titration)

ggplot(plottable,aes(x=factor(L1,levels=c("19_100_gfp","19_10_gfp")),y=value))+
  geom_boxplot(aes(fill=L1),width=0.8,outlier.size = 0.5)+
  scale_y_flowjo_biexp()+
  theme_bw()+
  xlab("sample")+
  rock_roi_theme()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+
  ylab("APC-A Atto647N")+
  scale_fill_manual(values=c("19_100_gfp"="#12783D",
                             "19_10_gfp"="#99CA3E"))
  
```

### Same for second sample

```{r,fig.width=8.1,fig.height=2.7}

storage_2<-read.flowSet(rdss2)

sampleNames(storage_2) <- gsub("Specimen_001_", "", sampleNames(storage_2))
sampleNames(storage_2) <- gsub(".fcs", "", sampleNames(storage_2))

# reordering data

storage_2<-storage_2[c(5,4,3,2,1)]

sampleNames(storage_2)<-c("pos_dt","pos_TSO","neg","100_gfp","10_gfp")
pData(storage_2)$name<-c("pos_dt","pos_TSO","neg","100_gfp","10_gfp")

# filtering data

sqrcut <- matrix(c(50000,70000,80000,90000,100000,110000,120000,110000,100000,90000,80000,70000,50000,
                   75000,110000,125000,120000,120000,115000,75000,50000,45000,43000,45000,50000,75000),ncol=2,nrow=13)

colnames(sqrcut) <- c("FSC-A","SSC-A")

beads2 <- polygonGate(filterId="beads", gate= sqrcut)

ggcyto(storage_2, aes(x = FSC.A, y = SSC.A)) + 
  geom_hex(bins = 100) + 
  facet_wrap(~factor(name, levels = c("100_gfp","10_gfp"))) +
  geom_gate(beads2) + 
  geom_stats(type = c("percent"),size = 2,adjust=c(0.7,1.2)) +
  theme_bw() +
  facs_rock_roi_theme_multiple_panels() 

gs <- GatingSet(storage_2) # create a GatingSet
gs_pop_add(gs, beads2,parent="root")
recompute(gs)

# check filtering 

filt_titration2 <- Subset(storage_2, beads2)

ggcyto(filt_titration2, aes(x = FSC.A, y = SSC.A)) + 
  geom_hex(bins = 100) + 
  facet_wrap(~factor(name, levels = c("pos_dt","pos_TSO","neg","100_gfp","10_gfp"))) +
  geom_gate(beads2) + 
  theme_bw() +
  facs_rock_roi_theme_multiple_panels()

ggcyto(filt_titration2, aes(x = "APC-A", fill = name,color=name)) + 
  geom_histogram(alpha = 1,bins=256) + 
  scale_x_flowjo_biexp() +
  facet_wrap(~factor(name, levels = c("pos_dt","pos_TSO","neg","100_gfp","10_gfp")),ncol=1,switch = "y")+
  theme_bw() +
  facs_hist_rock_roi_theme()+
  theme(strip.placement = "outside")+
  theme(legend.position = "none")+
  theme(strip.text = element_text(size=5,face="bold"))+
  force_panelsizes(rows = unit(0.25, "in"),
                   cols = unit(2.5, "in"))+
  theme(panel.spacing = unit(0.1, "lines"))+
  theme(strip.text.y = element_blank())+
  theme(axis.line = element_line())+
  scale_fill_manual(values=c(pos_dt="#882155",
                             pos_TSO="#CC6677",
                             neg="#C0C0C0",
                             "100_gfp"="#12783D",
                             "10_gfp"="#99CA3E"))+
    scale_color_manual(values=c(pos_dt="#882155",
                             pos_TSO="#CC6677",
                             neg="#C0C0C0",
                             "100_gfp"="#12783D",
                             "10_gfp"="#99CA3E"))

list_filt_titration<-list()

for (i in 1:length(filt_titration2)){
  list_filt_titration[[sampleNames(filt_titration2)[[i]]]]<-as.data.frame(filt_titration2[[i]]@exprs)$"APC-A"
}

plottable2<-melt(list_filt_titration)

ggplot(plottable2,aes(x=factor(L1,levels=c("pos_dt","pos_TSO","neg","100_gfp","10_gfp")),y=value))+
  geom_boxplot(aes(fill=L1),width=0.8,outlier.size = 0.5)+
  scale_y_flowjo_biexp()+
  theme_bw()+
  xlab("sample")+
  rock_roi_theme()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+
  ylab("APC-A Atto647N")+
  scale_fill_manual(values=c(pos_dt="#882155",
                             pos_TSO="#CC6677",
                             neg="#C0C0C0",
                             "100_gfp"="#12783D",
                             "10_gfp"="#99CA3E"))
  
```


### combining the two 

```{r,fig.width=8.1,fig.height=2.7}

combined<-rbind(plottable,plottable2)

ggplot(combined,aes(x=factor(L1,levels=c("pos_dt","pos_TSO","neg","100_gfp","10_gfp","19_100_gfp","19_10_gfp")),y=value))+
  geom_boxplot(aes(fill=L1),width=0.8,outlier.size = 0.5)+
  scale_y_flowjo_biexp()+
  theme_bw()+
  xlab("sample")+
  rock_roi_theme()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5))+
  ylab("APC-A Atto647N")+
  scale_fill_manual(values=c(pos_dt="#882155",
                             pos_TSO="#CC6677",
                             neg="#C0C0C0",
                             "100_gfp"="#12783D",
                             "10_gfp"="#99CA3E",
                             "19_100_gfp"="#12783D",
                             "19_10_gfp"="#99CA3E"))

```



### Session info

```{r}

sessionInfo()

```
